prevwong/craft.js

packages/docs/docs/guides/basic-tutorial.md
When I was trying [Basic Tutorial](https://craft.js.org/r/docs/guides/basic-tutorial) I found some typos.
=> docs: fix typo in Basic Tutorial

packages/docs/docs/api/UserComponent.md
Documentation said "canMoveout" instead of "canMoveOut"
=> Fix case on "canMoveOut"

packages/layers/src/index.tsx
In the layers package `useLayer` was not re-exported.  That resulted in project using `@craftjs/layers` not being able to use custom Layer rendering. This is the fix for that.
=> added missing export of useLayer in packages/layers

packages/core/src/editor/query.tsx, packages/core/src/events/EventManager.tsx
This PR implements the enhancements described in #10 
Changes made:
- New elements (via `connector.create`) are only added onDragEnd
- `query.getDropPlaceholder` accepts `source` to be either NodeId or Node. 
- The method is now able to test the acceptance of the newly created source Node (that is not yet in the editor state) against the target Node.
=> Improve creation of new elements

packages/core/src/nodes/Canvas.tsx
This PR closes #31 
Non-`children` prop changes to `<Canvas />` will be cascaded to the underlying User Element:
```jsx
const Container = () => {
const {connectors: {connect}} = useNode();
const [background, setBackground] = useState("#fff");
return (
<div ref={connect}>
<a onClick={() => setBackground("#000")}>Click</a>
// When background changes, MyCanvas will receive its updated value
<Canvas id="main" is={MyCanvas} background={background}>
<h3>Hi</h3>
</Canvas>
</div>
)
}
const MyCanvas = ({background}) => {
const {connectors: {connect}} = useNode();
return (
<div ref={connect} style={{background}}>
{children}
</div>
)
}
```
=> (#31) Fix reactivity for non-child props on <Canvas />

packages/utils/src/Handlers.ts, packages/utils/src/useMethods.ts
Closes #52 
Currently, the store's `Subscriber` triggers the collector (and subsequently its callback) when there is a state change. Hence, this causes an issue in #52  with dynamically created elements where a state change is required before the event handlers in the callback can be attached.
This PR enables the collector to be called when the Subscriber is created if the `collectOnCreate` parameter is set to true.
=> fix: allow Subscriber to collect state when created (#52)

packages/layers/src/layers/DefaultLayer/EditableLayerName.tsx
Closes issue #62 
The issue is caused by an effect hook in `<EditableLayerName />` that performs the `.setCustom` action on a given Node.  When a Node is deleted, the hook is called before `<EditableLayerName />` can be unmounted, thus performing an action on a deleted Node, which throws an error. 
This PR removes the need for the effect hook for changing layer names via the `.setCustom` action.
=> fix(layers): remove side effect

packages/core/src/editor/actions.ts
Fix for #64. Borrowing code from @mresposito's [fork](https://github.com/candulabs/craft.js/blob/master/packages/core/src/editor/actions.ts#L136-L140).
=> Deep clone target node data nodes during delete

packages/docs/docs/concepts/user-components.md
In user-components examples, there is a minor typo where closing Canvas tag is missing.
=> Minor typo in user-component docs

packages/core/src/events/EventHandlers.ts
fix: dropend remove Eventhandlers.envents.indicator
=> fix: dropend remove EventHandlers.events.indicator(#75)

packages/core/src/editor/NodeHelpers.ts, packages/core/src/editor/tests/NodeHelpers.test.ts, packages/core/src/tests/fixtures.ts, packages/core/src/utils/createTestNode.ts
- Prevent Node from being dragged into its own descendants at any level
- Call `canMoveOut` only if the Node is being dragged to a new parent
=> hotfix: isDroppable rules

packages/core/src/events/EventHandlers.ts, packages/core/src/events/tests/EventHandlers.test.ts, packages/utils/src/Handlers.ts
- Improvements to PR #85 
- Expose `e.stopCraftPropagation` rather than passing a flag. This is so we can maintain API similarity with DOM `addEventListener` 
- Fix bug that causes Handlers to work incorrectly when the editor is disabled and re-enabled again
=> fix: Handlers API

packages/core/src/events/EventHandlers.ts, packages/core/src/events/tests/EventHandlers.test.ts, packages/utils/src/Handlers.ts
Further fixes to make `stopPropagation` replicate its native behavior
- Disable only specific event from firing on ancestors. The existing approach disables any event on the parent(s) to fire. Instead, it should only disable events that are of the same name as the handler where `stopPropagation` is called.
- Disable events only on the ancestors of the element that is preventing propagation. The existing approach also prevents non-ancestor elements with the same handler/connector from firing.
=> fix: handle propagation by matching descendant

jest/setup.js, packages/core/src/editor/actions.ts, packages/core/src/nodes/Element.tsx, packages/core/src/nodes/tests/Element.test.tsx, packages/core/src/utils/createTestNode.ts
Fix for #98 
- Ensure existing linked Node is rendered correctly
=> fix: linked nodes hydration

packages/core/src/editor/query.tsx, packages/core/src/editor/tests/query.test.tsx, packages/core/src/interfaces/nodes.ts, packages/core/src/utils/createNode.ts, packages/core/src/utils/parseNodeFromJSX.tsx, packages/core/src/utils/tests/createNode.test.tsx, packages/core/src/utils/tests/parseNodeFromJSX.test.tsx, packages/docs/docs/api/useEditor.md
- Add `parseFreshNode` to allow developers to easily create new Node objects
- Fix `.custom` not loading default values correctly
=> feat: add parseFreshNode

packages/examples/landing/components/selectors/Video/index.tsx
removing it resolves the issue.
```[ error ] ERROR in /Users/ichenwu/code/landing/components/selectors/Video/index.tsx
38:11 No overload matches this call.
Overload 1 of 2, '(props: Readonly<YouTubeProps>): YouTube', gave the following error.
Type '{ width: string; height: string; showinfo: number; }' is not assignable to type 'Options'.
Object literal may only specify known properties, and 'showinfo' does not exist in type 'Options'.
Overload 2 of 2, '(props: YouTubeProps, context?: any): YouTube', gave the following error.
Type '{ width: string; height: string; showinfo: number; }' is not assignable to type 'Options'.
Object literal may only specify known properties, and 'showinfo' does not exist in type 'Options'.
36 |           width: '100%',
37 |           height: '100%',
> 38 | …
```
=> show info is throwing errors

packages/core/src/editor/Editor.tsx, packages/core/src/editor/store.tsx, packages/core/src/interfaces/editor.ts
This PR adds adds the ability to normalise Nodes on state change
=> feat: normalise nodes draft

packages/slate/src/utils/applyIdOnOperation.ts
Remove `set_node` op when generating new ids
=> fix: slate op

packages/slate/src/extend/editable/Element.tsx, packages/slate/src/extend/editable/RenderEditable.tsx
This PR remove the automatic attachment of drag connectors to all Slate Element node
- This is because Firefox/Safari do not work well with HTML elements that's both `draggable` and `contenteditable`. Hence, we expose a `drag` property to each Slate elements so the developer could handle the drag behaviour accordingly
=> fix: remove drag connector in slate

packages/core/src/editor/actions.ts
- Fixes editor crash when deserializing
=> hotfix: clear events prior to updating nodes state

packages/core/src/events/Events.tsx, packages/utils/src/Handlers.ts, packages/utils/src/RenderIndicator.tsx
This simple change allows using craftjs with an iframe that contains all the building nodes. 
It's important for me because I want to build a page that doesn't have the same style as the editor, so using an iframe allows to reset all the styles and start from scratch.
Some work needs to be done for the "packages/core/src/events/Events.tsx" file, because the "RenderIndicator" component should be rendered inside the iframe, not in the parent document.
I'm looking for a way to make the change as simple as possibile.
=> Fix handlers insertion when using an iframe

packages/utils/src/getDOMInfo.ts
Currently, `grid` user components have a different drag/drop interaction than `flex` – this PR adds `grid` to the list of display styles that enable `styleInFlow`.
=> feat: add grid to styleInFlow

packages/slate/src/normalization/getSplitOperations.ts, packages/slate/src/normalization/tests/getSplitOperations.test.ts, packages/slate/src/normalization/tests/splitSlate.test.ts
- Fix crash when a non-Slate node with a nested Slate child is dropped into another Slate parent
=> fix(slate): split operation bug

packages/utils/src/getDOMInfo.ts
Follow up from https://github.com/prevwong/craft.js/pull/151.
This PR fixes the CSS grid drag/drop jank:
https://user-images.githubusercontent.com/12195101/106777448-ff15df00-6612-11eb-998c-6cf5a4eaa000.mp4
=> fix: css grid drag and drop jank

packages/core/src/editor/actions.ts, packages/core/src/editor/store.tsx, packages/core/src/events/DefaultEventHandlers.ts, packages/core/src/interfaces/nodes.ts, packages/examples/basic/components/user/Card.js, packages/examples/basic/components/user/Container.js
This PR adds `draggedOver` to the `events`. It's almost the same as #37 but targets the `next` branch and the new EventHandlers, which also gives us a cleaner API. (#37 will be obsolete).
Since the new EventHandlers introduced a `Set` as the store for the EventHandlers, we can now store not only the id of the node we are dragging over, but all of its ancestors, too.
I also updated the Basic example with two different examples on how to make use of the new API.
Closes #28, #37, #183
---
The only complaint we have with the new API is the name `draggedOver`. @prevwong suggested to re-use the `hovered` event. If an element is being hovered, and the `dragged` event stores at least one nodeId, we are dragging over an element. I prefer a more explicit API over an implicit one. As a counter …
=> Added events.draggedOver part 2

packages/core/src/events/CoreEventHandlers.ts, packages/core/src/events/DefaultEventHandlers.ts, packages/utils/src/EventHandlers/ConnectorRegistry.ts, packages/utils/src/EventHandlers/EventHandlers.ts, packages/utils/src/EventHandlers/tests/EventHandlers.test.ts
With this PR #180 should be possible without the `useEffect` workaround.
It is now possible to use the following code:
```jsx
<MaterialButton
ref={(ref) => {
connectors.create(
ref,
<Button text="Click me" size="small" />,
// this will be called, when the node is dropped
(nodeTree) => {
// we can now select the node or do other stuff with it
actions.selectNode(nodeTree.rootNodeId);
}
);
}}
variant="contained"
>
Button
</MaterialButton>
```
---
To add this feature it was necessary to modify the `ConnectorRegistry`. I didn't want to change too much, that's why I added a `additionalArguments` attribute to the `ConnectorToRegistry` type and object. It would be possible to merge `opts` and `additionalArguments` and spread it instead of using …
=> feat: Added a callback function to connectors.create to get access to the added node

packages/core/package.json, packages/core/src/editor/tests/actions.test.ts, packages/core/src/interfaces/nodes.ts, packages/core/src/utils/createNode.ts, packages/core/src/utils/tests/createNode.test.tsx, packages/layers/src/events/LayerHandlers.ts, packages/utils/src/History.ts, packages/utils/src/useMethods.ts, yarn.lock
This PR fixes the regressions caused by updating immer in #211 
- Manually enable `immer` plugins
- `MapSet` => used by `state.events`  
-  `Patches` => used by History
- Accommodate immer auto-freeze 
- Fix unsafe object mutation in `LayerHandlers` 
- Remove the usage of `produce` in `createNode`
- Doing this also allows us to remove `immer` as a dependency from core
=> hotfix: migrate immer

cypress/integration/history.ts, packages/core/src/events/Events.tsx, packages/core/src/events/movePlaceholder.ts, packages/core/src/interfaces/editor.ts
This PR enables us to add additional indicator options, specifically controlling:
- the ability to override the default `0.2ms` transition
- the thickness of the rendered indicator
https://user-images.githubusercontent.com/12195101/110573151-c04ed980-8128-11eb-8d60-0c06eac6473a.mp4
=> feat: additional indicator options

packages/slate/src/extend/editable/useCraftStateSync.tsx
- When a Slate node is removed, ensure its' descendants are removed
=> fix: remove slate node

packages/layers/README.md, packages/layers/package.json
Basically I get this warning because of the fact there are two conflicting styled-components in the application
```
It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process and makes your application bigger without a good reason.
```
The changes made are as suggested on the styled-components docs
https://styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library
=> chore(layers): mark styled-components as external dependencies

packages/core/package.json, packages/core/src/utils/createNode.ts, packages/core/src/utils/getRandomNodeId.ts, packages/utils/package.json, packages/utils/src/EventHandlers/ConnectorRegistry.ts, packages/utils/src/getRandomId.ts, packages/utils/src/index.ts, yarn.lock
Issue #268 made me look into [shortid](https://www.npmjs.com/package/shortid) and I stumbled upon the deprecation message and the safety warning.
This PR replaces `shortid` with the suggested [`nanoid`](https://www.npmjs.com/package/nanoid). For existing projects old NodeIDs should still work but new ones would be generated with `nanoid`.
Only "disadvantage" if you can call it that, is that ids generated by `nanoid` are longer than `shortid`'s ids.
=> chore: replace package shortid with nanoid

packages/core/src/editor/EditorContext.tsx, packages/core/src/editor/useInternalEditor.ts, packages/core/src/hooks/tests/EditorContext.test.tsx, packages/core/src/nodes/useInternalNode.ts, packages/utils/src/constants.ts
Lately there were some issues resulting from users using `useEditor` and/or `useNode` outside of `<Editor />`.
This PR will throw an Error to warn the user.
Related:
#284
=> chore: add error when hooks is used outside of EditorContext

packages/core/src/utils/serializeNode.tsx
This fix addresses the issue when `type` is nested as a key on the data that is used, resolving the following issues/PRs:
https://github.com/prevwong/craft.js/issues/225 and https://github.com/prevwong/craft.js/pull/251
=> Fix: Nested "type" key in Element props leads to serialization error

packages/utils/package.json, yarn.lock
Bump immer version to include security fixes: https://github.com/immerjs/immer/releases/tag/v9.0.6
=> chore: bump immer

examples/basic/README.md
`npm dev` command doesn't exist now
`basic` folder location has changed. So fix it according to that.
=> Fix the paths and command

packages/core/src/interfaces/editor.ts, packages/core/src/store/actions.ts, packages/core/src/store/query/EditorQuery.ts, packages/core/src/store/query/NodeQuery.ts, packages/core/src/store/query/tests/EditorQuery.test.tsx, packages/core/src/store/query/tests/NodeQuery.test.ts, packages/core/src/utils/types.ts
This PR adds backwards compatibility for a couple of actions/query methods:
- `action.deserialize` supports both new and old serialized state
- `query.serialize` returns `Nodes` by default, but accepts an option to return legacy state
- `query.node().toNodeTree` returns NodeTree by default, but accepts an option to return LegacyNodeTree
- Since `query.parseFreshNode` is deprecated, we now expose a new `query.generateRandomNodeId()` for use cases involving create new nodes manually
=> fix: backwards compatibility bugs

packages/core/src/store/EditorStore.ts, packages/core/src/utils/removeNodeFromEvents.ts, packages/utils/src/Store/useCollector.tsx
Currently a separate `setState` is called in order to perform any normalisation following an Action. 
This PR performs normalisation in the same `setState` call as the Action that was called.
=> fix(v0.3.x): merge normalize state call

examples/landing/components/selectors/Resizer.tsx, packages/layers/src/layers/DefaultLayer/DefaultLayer.tsx, packages/layers/src/layers/DefaultLayer/DefaultLayerHeader.tsx, packages/layers/src/layers/DefaultLayer/EditableLayerName.tsx, packages/utils/src/Store/Store.ts
Wraps collectors in a try-catch block to prevent site from crashing when accessing a deleted Node's properties
=> hotfix(v0.3.x): try catch collector values

packages/core/src/nodes/Element.tsx, packages/core/src/nodes/NodeElement.tsx, packages/core/src/store/EditorStore.ts, packages/utils/src/History.ts, packages/utils/src/tests/History.test.ts
Currently, when we create new Linked Nodes when `<Element />` mounts, the action is not tracked in the history stack. Thus, when the user hits "Undo", the Linked Node won't be deleted.
This PR fixes the issue by replacing `actions.history.ignore().addLinkedNodeTree` with `actions.history.merge().addLinkedNodeTree` which merges the `addLinkedNodeTree` action with the previous history record (if any).
=> fix: linked nodes history

packages/core/src/events/CoreEventHandlers.ts, packages/core/src/events/DefaultEventHandlers.ts
issue: #316 
To save nodes as templates that can be dragged into the editor, userElement can be of type function that returns NodeTree.
Executed at the start of each drag to generate a new id for each node.
```
connectors.create(
ref,
// executed at the start of each drag to generate a new id for each node
() => {
const nodeTree = ...;
const newNodeId = getRandomId();
......
return nodeTree;
}
)
```
=> feat: support custom nodeTree in connectors.create()

site/src/components/Image.js
now, all images in [documentation](https://craft.js.org/docs/guides/basic-tutorial) are broken by redundant `%7D` in the end.
example:
- https://craft.js.org/img/tutorial/interface.png%7D
=> fix: remove redundant "}" of the image url

packages/core/src/editor/Editor.tsx
This PR allows users to pass a custom `EditorStore` when initialising Craft:
```tsx
import { EditorStore, Editor } from '@craftjs/core';
const App = () => {
const store = new EditorStore();
return (
<Editor store={store}>...</Editor>
)
}
```
This is useful when you need the `EditorStore` beforehand outside a React context. Otherwise, you would need to first set up the `<Editor />` component and access the store via `useEditor()`.
=> feat(v0.3.x): allow custom EditorStore

packages/core/src/index.tsx, packages/utils/src/History.ts
This PR adds the ability to listen for when a History operation is performed. This comes in handy if for example - you're building your own History manager and need a way to know when there's a undo/redo record available in Craft:
```tsx
import { EditorStory, HISTORY_OPERATION } from '@craftjs/core';
class YourCustomHistoryManager {
changes: [];
constructor(store: EditorStore) {
store.history.listen((op) => {
if ( op === HISTORY_OPERATION.ADD ) {
this.track({ isCraft: true });
}
});
}
track(change){
this.changes.push(change);
}
undo(change) {
if ( change.isCraft ) {
this.store.actions.history.undo();
return;
}
// handle other types of changes in your App
}
redo(change) {...}
}
=> feat(v0.3.x): add history event listener

packages/utils/src/EventHandlers/ConnectorRegistry.ts
This PR disables dnd when the Editor is initially disabled
Closes #373
=> fix: disable connectors when editor is disabled

packages/core/src/editor/Editor.tsx, packages/core/src/events/Events.tsx, packages/core/src/nodes/NodeContext.tsx, packages/core/src/nodes/NodeElement.tsx, packages/core/src/render/Frame.tsx, packages/core/src/render/RenderNode.tsx, packages/core/src/render/RenderPlaceholder.tsx
=> Add PropsWithChildren to Function Component prop interfaces in the core package

packages/core/src/editor/useInternalEditor.ts, packages/layers/src/layers/LayerContextProvider.tsx, packages/utils/src/EventHandlers/ConnectorRegistry.ts, packages/utils/src/EventHandlers/EventHandlers.ts, packages/utils/src/EventHandlers/interfaces.ts, packages/utils/src/EventHandlers/tests/DerivedEventHandlers.test.ts, packages/utils/src/EventHandlers/tests/EventHandlers.test.ts
Addresses issue with dnd in #404
=> fix: register event connectors on useEffect

packages/core/src/editor/Editor.tsx
Fix regression caused in #501 where `enabled` option is incorrectly set to undefined if the option was not explicitly specified in the `<Editor />` component
Closes #508
=> hotfix: optional enabled prop

packages/layers/src/events/RenderLayerIndicator.tsx
Resolves issue where the indicator would be a negative width if the `Layers` plugin was not placed on the left-hand side of the screen. This was due to `getBoundingClientRect()` calculating the `headingPos` realtive to the viewport. This change accounts for the `Layers` component placed anywhere in the viewport by adding back in the postion of the layer parent item.
See screenshot for real-world implementation that caused the indicator to the inccorect width due to the `Layers` component being used elsewhere in the viewport:
=> Resolve issue with indicator width:

packages/layers/src/events/LayerHandlers.ts
Fixes #562
This PR resolves an issue in the layers package where a node was not able to be placed within a container using the layers drag and drop interface when the accepting container had no children
=> (layers) Fix for dropping nodes into empty container

.changeset/old-chicken-lay.md, packages/core/src/render/Frame.tsx
=> fix: orphaned nodes when parsing from Frame's children in strict mode

site/docs/api/Editor.md
Added an example to the docs of how users can override the default Editor event handlers.
Note: Unlike the other examples, the code does include TypeScript types, let me know if you want the example to be JSX instead.
=> chore(doc): add an example for overriding Editor event handlers

.changeset/rude-bees-deliver.md, packages/core/src/editor/Editor.tsx, packages/core/src/events/DefaultEventHandlers.ts
Added `mouseleave` to default hover event handler, the `hovered` state gets removed when this is triggered.
Previously, if you wanted to removed the `hovered` state, you'd have to add something like
`ref={(ref: HTMLDivElement) => connectors.select(connectors.hover(ref, ''), '')}`
to a parent container to deselect/remove the hover state when the mouse pointer clicks/is outside of a node.
Also updated the `useEffect` in `packages/core/src/editor/Editor.tsx` due to lint error.
=> feat: remove node hovered state on mouseleave event

.changeset/shaggy-planets-camp.md, packages/core/src/events/createShadow.ts
Related to: https://github.com/prevwong/craft.js/issues/519
Fixes Safari drag shadow bug, where it is not visible when dragging. By changing display property to `absolute`, `background` is required as it will otherwise be transparent. By default I set the background to white. If any user wants to modify drag shadow css, I added additional classes `drag-shadow` and `drag-shadow-container`.
=> fix: drag shadow on Safari

site/docs/api/Frame.md
Fixes the Frame docs [Loading from serialized nodes](https://craft.js.org/docs/api/frame#loading-from-serialized-nodes) section. Now the example JSON provided in the data prop is bad formatted needs one more curly brace at the end. This curly brace is added on the PR, now the Frame docs example works well.
=> fix: <Frame> docs bad json provided to data prop

.changeset/blue-goats-cheer.md, packages/layers/src/layers/DefaultLayer/DefaultLayerHeader.tsx
The current animation of the chevron misplaces it in the layout and looks somewhat broken. 
This PR addresses this by centering the svg in the link container and setting the transform-origin to its direct center.
**Before:**
https://github.com/prevwong/craft.js/assets/45669613/e7877f1d-230b-4f53-be34-ac69dfb12f08
**After:**
https://github.com/prevwong/craft.js/assets/45669613/27584cd3-8e7c-4770-b792-f24dda109e10
=> fix: defaultLayerHeader chevron rotation

.changeset/many-toys-rescue.md, packages/core/src/events/Positioner.ts
=> fix: prevent delay when drop element outside of Editor frame

.changeset/sixty-rice-build.md, packages/core/src/editor/actions.ts
=> fix: make parentId param optional in actions.add()

site/docs/guides/basic-tutorial.md
In the useNode hook, both the selected and dragged are of type boolean, rather than array
=> chore(docs): update type of state.events.selected in useNode hook

.changeset/real-glasses-cross.md, packages/core/src/nodes/Element.tsx, packages/core/src/nodes/tests/Element.test.tsx, packages/core/src/render/Frame.tsx
Before these changes, the Frame and Element components delayed rendering user components until after the first render due to their reliance on useEffect. This meant that (a) server-side rendering did not work (b) pages with many deeply nested components took many render iterations to fully render a page which on slower devices would cause a visible layout shift.
After these changes neither Element nor Frame rely on useEffect.
Resolves:
- #140
- #200 
- #42
=> feat: SSR support

.changeset/serious-garlics-refuse.md, packages/core/src/editor/Editor.tsx, packages/core/src/events/Events.tsx, packages/core/src/nodes/NodeContext.tsx, packages/core/src/nodes/NodeElement.tsx, packages/core/src/render/Frame.tsx, packages/core/src/render/RenderNode.tsx, packages/core/src/render/RenderPlaceholder.tsx, packages/layers/src/events/RenderLayerIndicator.tsx, packages/layers/src/index.tsx, packages/layers/src/layers/DefaultLayer/DefaultLayer.tsx, packages/layers/src/layers/DefaultLayer/DefaultLayerHeader.tsx, packages/layers/src/layers/LayerContextProvider.tsx, packages/layers/src/layers/LayerIndicator.tsx, packages/layers/src/layers/LayerNode.tsx, packages/layers/src/manager/LayerManagerProvider.tsx, packages/utils/src/RenderIndicator.tsx
Cleanup component prop types - removing `React.FC`
=> chore: cleanup React.FC prop types

examples/landing/components/selectors/Text/TextSettings.tsx
=> fix(site): Typography panel summary stuck on "Bold"

.changeset/modern-socks-retire.md, packages/core/src/events/RenderEditorIndicator.tsx, packages/core/src/interfaces/editor.ts, packages/utils/src/RenderIndicator.tsx, site/docs/api/Editor.md
Closes #437 
Allow passing `style` and `className` as indicator options:
```tsx
<Editor 
indicator={{ style: {...}, className: "..." }}
/>
```
=> feat: allow customising dnd indicator classname/style

.changeset/smooth-elephants-clean.md, packages/core/src/events/CoreEventHandlers.ts, packages/core/src/events/DefaultEventHandlers.ts, packages/layers/src/events/LayerHandlers.ts
I noticed that `removeHoverOnMouseleave` wasn't working in the Layers, to get this working I basically just piggy-backed on the same option that is used in the core package and applied the relevant listener.
```ts
if (this.derived.options.removeHoverOnMouseleave) {
unbindMouseleave = this.addCraftEventListener(
el,
'mouseleave',
(e) => {
e.craft.stopPropagation();
layerStore.actions.setLayerEvent('hovered', null);
}
);
}
```
Not 100% sure on the change of adding the option to the type of the [CoreEventHandlers]( https://github.com/itsbjoern/craft.js/blob/4a20cff03a911a062a8bdf3fa523672bcc450d61/packages/core/src/events/CoreEventHandlers.ts#L11) but as far as I can tell that resolves any type issues on the derived handler type.
Also, as part of it I snuck in a small fix, as far as I can …
=>  feat: allow layers to utilise CoreEventHandler mouseleave options

site/docs/concepts/user-components.md
Fix typo.
Change "allow the user the edit the currently" to "allow the user to edit the currently"
=> Fix typo in core concepts docs, user-components.md

site/docs/api/useEditor.md
Added `actions.history.merge` method and `actions.history.throttle` descriptions for clarity in the api reference doc
=> chore(docs): update history methods api doc
