prevwong/craft.js

- packages/core/src/editor/actions.ts
> Deserialize hidden value

- packages/layers/src/events/index.tsx
Hi @prevwong 
please help to review this hotfix
Thanks
> fix: indicator width over the line

- packages/core/src/editor/Editor.tsx
- packages/core/src/editor/store.tsx
- packages/core/src/hooks/tests/useEditor.test.tsx
- packages/core/src/hooks/useEditor.tsx
- packages/core/src/interfaces/editor.ts
- packages/core/src/nodes/Element.tsx
- packages/core/src/nodes/tests/Element.test.tsx
- packages/core/src/nodes/useInternalNode.ts
- packages/core/src/render/Frame.tsx
- packages/core/src/render/tests/Frame.test.tsx
- packages/docs/docs/api/useEditor.md
- packages/docs/docs/api/useNode.md
- packages/examples/basic/components/Topbar.js
- packages/examples/basic/components/user/Container.js
- packages/examples/basic/components/user/Text.js
- packages/utils/src/History.ts
- packages/utils/src/index.ts
- packages/utils/src/tests/History.test.ts
- packages/utils/src/useMethods.ts
This PR adds undo/redo functionalities
[Demo](https://deploy-preview-117--craftjs.netlify.app/examples/basic/)
[Docs](https://deploy-preview-117--craftjs.netlify.app/r/docs/next/api/useEditor)
> feat: Implement history api

- packages/core/src/utils/serializeNode.tsx
This fixes https://github.com/prevwong/craft.js/issues/110
I haven't added any tests, as I noticed there were already none for this function. I can add some if you want.
> fix: serializeNode was naively checking if values were falsey

- packages/core/src/editor/actions.ts
- packages/core/src/editor/query.tsx
- packages/core/src/editor/tests/actions.test.ts
- packages/core/src/editor/tests/query.test.tsx
- yarn.lock
This PR adds the following:
- `getState` query to return the entire `EditorState`
- `setState` action to allow developers to freely manipulate the `EditorState`
- Update docs
- Improve `setState` api
> feat: add getState and setState

- packages/core/src/editor/EventHelpers.ts
- packages/core/src/editor/NodeHelpers.ts
- packages/core/src/editor/actions.ts
- packages/core/src/editor/query.tsx
- packages/core/src/editor/store.tsx
- packages/core/src/editor/tests/EventHelpers.test.ts
- packages/core/src/editor/tests/actions.test.ts
- packages/core/src/events/DefaultEventHandlers.ts
- packages/core/src/events/Events.tsx
- packages/core/src/events/createShadow.ts
- packages/core/src/events/tests/DefaultEventHandlers.test.ts
- packages/core/src/interfaces/editor.ts
- packages/core/src/interfaces/nodes.ts
- packages/core/src/nodes/index.ts
- packages/core/src/utils/getNodesFromSelector.ts
- packages/core/src/utils/isObject.ts
- packages/core/src/utils/removeNodeFromEvents.ts
- packages/core/src/utils/tests/getNodesFromSelector.test.ts
- packages/examples/basic/components/SettingsPanel.js
- packages/examples/basic/components/user/Card.js
- packages/examples/landing/components/editor/RenderNode.tsx
- packages/examples/landing/components/editor/Toolbar/index.tsx
- packages/layers/src/layers/DefaultLayer/DefaultLayerHeader.tsx
- packages/layers/src/layers/LayerNode.tsx
This PR adds the ability to select and drag multiple elements
> feat: add multi-select

- .github/workflows/codeql-analysis.yml
- .github/workflows/next.yml
- .github/workflows/pull-request.yml
- package.json
- on each push to next branch, prerelease version will be published to npm
- on PR to develop and next, run code analysis workflow
> Adds github job to prerelease next on push

- packages/utils/src/History.ts
> fix: History throttle

- packages/core/package.json
- packages/layers/package.json
- packages/utils/package.json
- packages/utils/src/useMethods.ts
- yarn.lock
Fixes lodash dependency (#165)
> chore: fix dependencies

- packages/slate/src/extend/editable/useCraftStateSync.tsx
- Delete orphaned Slate nodes from Craft's state
> fix(slate): delete orphaned nodes

- packages/core/src/editor/actions.ts
- packages/core/src/editor/store.tsx
- packages/core/src/events/DefaultEventHandlers.ts
- packages/core/src/interfaces/nodes.ts
- packages/examples/basic/components/user/Card.js
- packages/examples/basic/components/user/Container.js
> Revert "Added events.draggedOver part 2"

- packages/core/src/events/Events.tsx
- packages/utils/src/EventHandlers/ConnectorRegistry.ts
- packages/utils/src/EventHandlers/tests/EventHandlers.test.ts
> fix: handlers enabled when options.enabled=false

- packages/docs/docs/api/Element.md
- packages/docs/docs/api/Node.md
- packages/docs/docs/api/NodeHelpers.md
- packages/docs/docs/concepts/editor-components.md
- packages/docs/docs/concepts/user-components.md
- packages/docs/docs/guides/basic-tutorial.md
Scope of changes is restricted to docs only
> fix(docs): corrects various typos in project documentation

- packages/core/src/editor/actions.ts
Removes linked nodes when parent node is deleted
Fixes #176 #179 #228
> fix: orphaned linked nodes

- packages/core/src/editor/actions.ts
- packages/slate/src/extend/editable/useCraftStateSync.tsx
* Improve speed of slate/craft integration by avoiding registering the changes twice
> feat(slate): improve speed of slate/craft integration

- packages/layers/src/layers/LayerNode.tsx
Fixes bad setState call in LayerNode
Closes #203
> fix: bad setState in LayerNode

- packages/utils/src/History.ts
- packages/utils/src/useMethods.ts
> feat: clear history

- packages/core/src/editor/actions.ts
Closes #255 #277 
Fix issues relating to add nodes action in strict-mode
> fix: readonly parent error

- packages/core/src/editor/Editor.tsx
Closes #149
- Updates Editor's options as a side-effect.
> fix: sync <Editor /> props with state options

- packages/core/src/editor/actions.ts
- packages/core/src/editor/query.tsx
- packages/core/src/utils/resolveComponent.ts
- packages/utils/src/constants.ts
Prevents a common production error when a User Component is missing from resolver.
> feat: throw error if component is missing from resolver

- site/docs/api/EditorState.md
- site/docs/api/Node.md
- site/docs/api/NodeHelpers.md
- site/docs/api/UserComponent.md
- site/docs/guides/basic-tutorial.md
- site/docs/migrating/0.1.x.md
- site/sidebars.js
- site/src/components/Image.js
Update docs to reflect multi-select changes
> chore(docs): update docs for v0.2.x

- packages/core/src/editor/Editor.tsx
- packages/core/src/editor/actions.ts
- packages/core/src/editor/store.tsx
- packages/core/src/interfaces/editor.ts
> feat: add onBeforeMoveEnd

- packages/core/src/events/DefaultEventHandlers.ts
> fix(0.1.x): set drag state onDragStart

- packages/core/package.json
- packages/layers/package.json
- packages/utils/package.json
- yarn.lock
> chore: allow react 17 as peer dep

- packages/layers/package.json
- yarn.lock
> chore(layers@0.3.x): craft core peer dep

- packages/layers/package.json
- yarn.lock
> chore(layers): add react-contenteditable as dep

- site/docs/guides/basic-tutorial.md
> chore(docs): update state.events.selected type

- packages/layers/src/layers/useLayer.tsx
- packages/layers/src/manager/actions.tsx
> feat(layers): add set expanded state

- packages/utils/src/useMethods.ts
Fixes issue mentioned in #404 where an input field's caret position jumps to the end as the user starts typing. This issue is only present in React v18 and in Craft v0.2.x. 
View this [comment](https://github.com/prevwong/craft.js/issues/404#issuecomment-1195840239) for more info.
> fix: input field caret jumps in react 18

- packages/core/src/utils/serializeNode.tsx
Adds #308 fix (merged in 0.1.x branch) to 0.2.x branch
> fix: Nested "type" key in Element props leads to serialization error

- packages/core/src/editor/Editor.tsx
Certain options are missing in the `<Editor />` component props, which prevents consumers from customising certain options such as specifying a custom `EventHandler`
> fix: missing options in <Editor /> props

- packages/layers/src/index.tsx
> chore: export default layer components

- .changeset/two-windows-remain.md
- packages/core/src/editor/store.tsx
- packages/core/src/events/DefaultEventHandlers.ts
> feat: add option remove hover state on mouseleave
